WITH CollegesBeforeToday (INSTITUTION, ACAD_GROUP, EFFDT)
AS
(
	SELECT
		INSTITUTION,
		ACAD_GROUP,
		EFFDT
	FROM
		ps_new.PS_ACAD_GROUP_TBL
	WHERE
		EFF_STATUS = 'A'	AND
		EFFDT <= GETDATE()
),
MaxCollegesBeforeToday (INSTITUTION, ACAD_GROUP, EFFDT)
AS
(
	SELECT 
		INSTITUTION,
		ACAD_GROUP,
		MAX(EFFDT) AS EFFDT
	FROM
		CollegesBeforeToday
	GROUP BY
		INSTITUTION, ACAD_GROUP
)
SELECT
	  ACAD.INSTITUTION
	, ACAD.ACAD_GROUP
	, ACAD.EFFDT
	, ACAD.SRC_SYS_ID
	, ACAD.EFF_STATUS
	, ACAD.DESCR
	, ACAD.DESCRSHORT
	, ACAD.STDNT_SPEC_PERM
	, ACAD.AUTO_ENRL_WAITLIST
	, ACAD.LOAD_ERROR
	, ACAD.DATA_ORIGIN
	, ACAD.CREATED_EW_DTTM
	, ACAD.LASTUPD_EW_DTTM
	, ACAD.BATCH_SID
FROM 
	MaxCollegesBeforeToday MXCOL
		INNER JOIN ps_new.PS_ACAD_GROUP_TBL ACAD	ON MXCOL.INSTITUTION = ACAD.INSTITUTION
													AND MXCOL.ACAD_GROUP = ACAD.ACAD_GROUP
													AND MXCOL.EFFDT = ACAD.EFFDT

													




													

SELECT
  INSTITUTION
, ACAD_GROUP
, EFFDT
, SRC_SYS_ID
, EFF_STATUS
, DESCR
, DESCRSHORT
, STDNT_SPEC_PERM
, AUTO_ENRL_WAITLIST
, LOAD_ERROR
, DATA_ORIGIN
, CREATED_EW_DTTM
, LASTUPD_EW_DTTM
, BATCH_SID
FROM ps_new.PS_ACAD_GROUP_TBL
