WITH JobRecordsBeforeToday (EFFDT, EMPLID, EMPL_RCD)
AS
(
	SELECT
		EFFDT, 
		EMPLID,
		EMPL_RCD
	FROM
		ps_new.PS_JOB		
	WHERE
		EFFDT <= GETDATE()		-- Effective data is today or before (prevents future dating)
),
JobCodeRecordsBeforeToday (EFFDT, SETID, JOBCODE)
AS
(
	SELECT 
		EFFDT, 
		SETID, 
		JOBCODE
	FROM 
		ps_new.PS_JOBCODE_TBL
	WHERE
		EFFDT <= GETDATE()		AND
		EFF_STATUS = 'A'
),
PositionRecordsBeforeToday (EFFDT, POSITION_NBR)
AS
(
	SELECT
		EFFDT,
		POSITION_NBR
	FROM
		ps_new.PS_POSITION_DATA
	WHERE
		EFFDT <= GETDATE()		AND
		EFF_STATUS = 'A'
)
SELECT psjv.EMPLID, psjv.EMPL_RCD, psj2.DEPTID, psjc2.DESCRSHORT AS TITLE_ABBRV, psjc2.DESCR AS TITLE, psp2.DESCR AS WORKING_TITLE,
   NULL AS TITLE_GRP_ID_CODE, psj2.JOBCODE, NULL AS BUSINESS_UNIT, NULL AS "ORGANIZATION", NULL AS FUND, NULL AS "ACCOUNT",
   psjc2.JOB_FUNCTION AS "FUNCTION", NULL AS "PROJECT", NULL AS "PROGRAM", NULL AS "USER_DEFINED", NULL AS BUDGET_YEAR, NULL AS PRIM_APPT_CODE,
   CAST(NULL AS INTEGER) AS APPT_PERCENT, NULL AS APPT_SEQ_CODE, NULL AS SUMMER1_SERVICE, NULL AS WINTER_SERVICE, NULL AS AUTUMN_SERVICE,
   NULL AS SPRING_SERVICE, NULL AS SUMMER2_SERVICE, CAST(NULL AS DATETIME) AS OSU_LEAVE_START_DATE, psj2.ASGN_END_DT AS APPT_END_DATE, psp2.OS_APPT_LENGTH AS APPT_END_LENGTH,
   psj2.ASGN_START_DT AS APPT_START_DATE,
   CAST(NULL AS DATETIME) AS DW_CHANGE_DATE, NULL AS DW_CHANGE_CODE, psj2.SAL_ADMIN_PLAN
FROM (
   SELECT psji.EFFDT, psji.EMPLID, psji.EMPL_RCD, MAX(pst.EFFSEQ) AS EFFSEQ
   FROM (SELECT MAX(EFFDT) AS EFFDT, EMPLID, EMPL_RCD 
         FROM JobRecordsBeforeToday
         GROUP BY EMPLID, EMPL_RCD) psji
   INNER JOIN ps_new.PS_JOB pst ON psji.EFFDT = pst.EFFDT AND psji.EMPLID = pst.EMPLID AND psji.EMPL_RCD = pst.EMPL_RCD
   GROUP BY psji.EFFDT, psji.EMPLID, psji.EMPL_RCD
) psjv
INNER JOIN ps_new.PS_JOB psj2 ON psjv.EFFDT = psj2.EFFDT AND psjv.EMPLID = psj2.EMPLID AND psjv.EMPL_RCD = psj2.EMPL_RCD AND psjv.EFFSEQ = psj2.EFFSEQ
INNER JOIN (
   SELECT MAX(psjci.EFFDT) AS EFFDT, psjci.SETID, psjci.JOBCODE
   FROM JobCodeRecordsBeforeToday psjci
   GROUP BY psjci.SETID, psjci.JOBCODE
) psjcv ON psj2.JOBCODE = psjcv.JOBCODE
INNER JOIN ps_new.PS_JOBCODE_TBL psjc2 ON psjcv.JOBCODE = psjc2.JOBCODE AND psjcv.EFFDT = psjc2.EFFDT AND psjcv.SETID = psjc2.SETID
INNER JOIN (
   SELECT MAX(pspi.EFFDT) AS EFFDT, pspi.POSITION_NBR
   FROM PositionRecordsBeforeToday pspi
   GROUP BY pspi.POSITION_NBR
) pspv ON psj2.POSITION_NBR = pspv.POSITION_NBR
INNER JOIN ps_new.PS_POSITION_DATA psp2 ON pspv.POSITION_NBR = psp2.POSITION_NBR AND pspv.EFFDT = psp2.EFFDT
WHERE psj2.EMPL_STATUS = 'A'






SELECT psjv.EMPLID, psjv.EMPL_RCD, psj2.DEPTID, psjc2.DESCRSHORT AS TITLE_ABBRV, psjc2.DESCR AS TITLE, psp2.DESCR AS WORKING_TITLE,
   NULL AS TITLE_GRP_ID_CODE, psj2.JOBCODE, NULL AS BUSINESS_UNIT, NULL AS "ORGANIZATION", NULL AS FUND, NULL AS "ACCOUNT",
   psjc2.JOB_FUNCTION AS "FUNCTION", NULL AS "PROJECT", NULL AS "PROGRAM", NULL AS "USER_DEFINED", NULL AS BUDGET_YEAR, NULL AS PRIM_APPT_CODE,
   CAST(NULL AS INTEGER) AS APPT_PERCENT, NULL AS APPT_SEQ_CODE, NULL AS SUMMER1_SERVICE, NULL AS WINTER_SERVICE, NULL AS AUTUMN_SERVICE,
   NULL AS SPRING_SERVICE, NULL AS SUMMER2_SERVICE, CAST(NULL AS DATETIME) AS OSU_LEAVE_START_DATE, psj2.ASGN_END_DT AS APPT_END_DATE, psp2.OS_APPT_LENGTH AS APPT_END_LENGTH,
   psj2.ASGN_START_DT AS APPT_START_DATE,
   CAST(NULL AS DATETIME) AS DW_CHANGE_DATE, NULL AS DW_CHANGE_CODE, psj2.SAL_ADMIN_PLAN
FROM (
   SELECT psji.EFFDT, psji.EMPLID, psji.EMPL_RCD, MAX(pst.EFFSEQ) AS EFFSEQ
   FROM (SELECT MAX(EFFDT) AS EFFDT, EMPLID, EMPL_RCD 
         FROM ps_new.PS_JOB
         GROUP BY EMPLID, EMPL_RCD) psji
   INNER JOIN ps_new.PS_JOB pst ON psji.EFFDT = pst.EFFDT AND psji.EMPLID = pst.EMPLID AND psji.EMPL_RCD = pst.EMPL_RCD
   GROUP BY psji.EFFDT, psji.EMPLID, psji.EMPL_RCD
) psjv
INNER JOIN ps_new.PS_JOB psj2 ON psjv.EFFDT = psj2.EFFDT AND psjv.EMPLID = psj2.EMPLID AND psjv.EMPL_RCD = psj2.EMPL_RCD AND psjv.EFFSEQ = psj2.EFFSEQ
INNER JOIN (
   SELECT MAX(psjci.EFFDT) AS EFFDT, psjci.SETID, psjci.JOBCODE
   FROM ps_new.PS_JOBCODE_TBL psjci
   GROUP BY psjci.SETID, psjci.JOBCODE
) psjcv ON psj2.JOBCODE = psjcv.JOBCODE
INNER JOIN ps_new.PS_JOBCODE_TBL psjc2 ON psjcv.JOBCODE = psjc2.JOBCODE AND psjcv.EFFDT = psjc2.EFFDT AND psjcv.SETID = psjc2.SETID
INNER JOIN (
   SELECT MAX(pspi.EFFDT) AS EFFDT, pspi.POSITION_NBR
   FROM ps_new.PS_POSITION_DATA pspi
   GROUP BY pspi.POSITION_NBR
) pspv ON psj2.POSITION_NBR = pspv.POSITION_NBR
INNER JOIN ps_new.PS_POSITION_DATA psp2 ON pspv.POSITION_NBR = psp2.POSITION_NBR AND pspv.EFFDT = psp2.EFFDT
WHERE psj2.EMPL_STATUS = 'A'